### ISSUE TITLE
Practice problems won't load

### ISSUE THREAD

**Issue by psteckler** [appirio-tech/arena-web#588]
When trying to look at the practice problems, I see a timeout message, and then the list of problems is empty.

**Comment by prasook-jain** [comment]
same here , I'm getting these problem from a month ago...

**Comment by leanne63** [comment]
Same here - unresponsive script message from Firefox, and nothing loading even when okaying script to continue. Note: the list of practice problems appears; when selecting a problem, the Problem and Coding Areas appear; but the Problem Area shows: "Please wait while the requested problem is loaded. This may take several minutes ..."

**Comment by njulie** [comment]
the practice problems aren't loading for me either - it says "malformed auth header"

**Comment by bjesper** [comment]
Same here. I am also getting the "malformed auth header" message.

**Comment by roman-bl** [comment]
@njulie  same for me as well. "malformed auth header".  Wander when it will get fixed.

**Comment by 0xfb** [comment]
I experience exactly the same as leanne63 on Firefox... haven't tried other browsers though.

**Comment by FatihC** [comment]
I got "Timeout" then I got this:

Failed to get practice problem: Error running instance method java.sql.SQLException: System or internal error java.net.SocketTimeoutException: Read timed out at com.informix.util.IfxErrMsg.getSQLException(IfxErrMsg.java:482) at com.informix.jdbc.IfxSqli.a(IfxSqli.java:9172) at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2513) at com.informix.jdbc.IfxSqli.a(IfxSqli.java:1760) at com.informix.jdbc.IfxSqli.executeStatementQuery(IfxSqli.java:1698) at com.informix.jdbc.IfxSqli.executeStatementQuery(IfxSqli.java:1629) at com.informix.jdbc.IfxResultSet.a(IfxResultSet.java:206) at com.informix.jdbc.IfxStatement.executeQueryImpl(IfxStatement.java:1228) at com.informix.jdbc.IfxStatement.executeQuery(IfxStatement.java:218) at snaq.db.CachedStatement.executeQuery(CachedStatement.java:172) at com.topcoder.node.jdbc.InformixWrapper.executeQuery(InformixWrapper.java:87) at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:606) Caused by: java.net.SocketTimeoutException: Read timed out at java.net.SocketInputStream.socketRead0(Native Method) at java.net.SocketInputStream.read(SocketInputStream.java:152) at java.net.SocketInputStream.read(SocketInputStream.java:122) at java.io.BufferedInputStream.fill(BufferedInputStream.java:235) at java.io.BufferedInputStream.read1(BufferedInputStream.java:275) at java.io.BufferedInputStream.read(BufferedInputStream.java:334) at com.informix.asf.IfxDataInputStream.readFully(IfxDataInputStream.java:139) at com.informix.asf.IfxDataInputStream.readSmallInt(IfxDataInputStream.java:446) at com.informix.jdbc.IfxSqli.receiveMessage(IfxSqli.java:2489) ... 11 more

**Comment by zafartahirov** [comment]
Tried Safari 9, Firefox 43/44, Chrome 48 - not loading

```
Error: balloonsData[$scope.key] is undefined
[6]</balloonCtrl</<@https://arena.topcoder.com/js/bundle.js:2491:17
$http/promise.success/<@https://arena.topcoder.com/js/bundle.js:38466:11
qFactory/defer/deferred.promise.then/wrappedCallback@https://arena.topcoder.com/js/bundle.js:41977:31
qFactory/defer/deferred.promise.then/wrappedCallback@https://arena.topcoder.com/js/bundle.js:41977:31
qFactory/ref/<.then/<@https://arena.topcoder.com/js/bundle.js:42063:26
$RootScopeProvider/this.$get</Scope.prototype.$eval@https://arena.topcoder.com/js/bundle.js:43106:16
$RootScopeProvider/this.$get</Scope.prototype.$digest@https://arena.topcoder.com/js/bundle.js:42918:15
$RootScopeProvider/this.$get</Scope.prototype.$apply@https://arena.topcoder.com/js/bundle.js:43210:13
done@https://arena.topcoder.com/js/bundle.js:38745:34
completeRequest@https://arena.topcoder.com/js/bundle.js:38959:7
createHttpBackend/</xhr.onreadystatechange@https://arena.topcoder.com/js/bundle.js:38898:1
nrWrapper@https://arena.topcoder.com/js/newrelic.js:1:11167
```

**Comment by jeffswt** [comment]
Refer to this issue: #673.
